### PR TITLE
Rough draft of contact-us form for architecture review.

### PR DESCRIPTION
**Pull request by mccalluc**
@afred: architecture review, please. The contact-us page needs to be a lot like the other "about" pages... but it's different. Is this a good way of doing it?

(tests aren't running for me locally. Separate email.)

### CODE REVIEW

**Comment by mccalluc** [comment]
@afred ?

**Comment by afred** [comment]
@mccalluc i think this looks good. I modified the test description of the `About` models. I don't mean to be nitpicky, but I really rely on those test messages to help me understand what's going on.

**Comment by afred** [comment]
@mccalluc of course, this will break if you try to submit the contact form, right? There is no `ContactUsController#new` method to handle the form submission.

**Comment by mccalluc** [comment]
Yeah, actually hooking it up to a mailer is still todo.

**Pull request merged**
