### PR TITLE
3 logos

### PR DESCRIPTION
**Pull request by mccalluc**
Sizes of the images I was given were all over the place. Frontline, in particular, is too small. But this is the right direction, at least. @afred : please review.

screen shot 2015-09-25 at 2 35 34 pm

### CODE REVIEW

**Comment by lisarosenthal** [comment]
I can help out with sizing the logos, just let me know...

**Comment by lisarosenthal** [comment]
amex2
nova2
frontline2
These should be sized well for the collection page banners.

**Comment by afred** [comment]
and here's what they look like with a background...
image

**Comment by mccalluc** [comment]
New logos uploaded to S3. same filenames. Looks good. (Would have been better to open a new ticket for this to be sure it doesn't get lost.)

**Pull request merged**
