### PR TITLE
two-mode-banner + svg-logo

### PR DESCRIPTION
**Pull request by mccalluc**
@afred : please review. Two distinct things:
- The navbar needs a homepage mode, and a non-home mode. This does that.
- The SVG is a tiny bit gratuitous, but it will make it so much easier if we need to change size, or wording, or color down the line.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc don't we need the SVG to include the "Stock Sales & Licensing" moniker? Or was your plan to overly text?

**Comment by afred** [comment]
@mccalluc also.. what's the best way to view an SVG? When i view the file in github, it looks like this:
image
and when I copy the source to my local machine, and view it in a browser, it looks like this...
image
and I'm not sure of what other app to view it in... Preview doesn't work.

**Comment by lisarosenthal** [comment]
We need to make sure that however you handle the Stock Sales logo, the proportions of the WGBH logo to the text is maintained for branding purposes. That's why it might be better to use the png and scale it down for smaller browser widths (?) I'm noticing now that it getting squished horizontally in mobile view.

**Comment by mccalluc** [comment]
(fixes #28)

**Comment by afred** [comment]
@mccalluc the cropped version of the logo I was seeing in chrome is apparently due to the `height="70"`. I increased that and was able to see the text. Does that need to happen in order to correctly display on the website?

**Comment by mccalluc** [comment]
@afred review. Not sure why SVG preview here is weird, but looks good in context.

**Pull request merged**
