### PR TITLE
Program records

### PR DESCRIPTION
**Pull request by mccalluc**
@AlisonCSmith : Here are some changes that make it possible to have a special view for programs.
- Are you comfortable combining the two databases? Do you have other fields you want to present?
- What should we do about the dissimilarity in image sizes?
- Do you have any other series besides these three?
- What kind of fine-print do you want about costs?

screen shot 2016-06-29 at 2 41 45 pm

screen shot 2016-06-29 at 2 42 31 pm

### CODE REVIEW

**Comment by AlisonCSmith** [comment]
Hi Chuck:
1.  Not sure I understand what you mean by your question "are you comfortable combining the 2 databases"?
2.  Image sizes;  Will it look too ragged to just leave them as different sizes? And/or screw us up in terms of layout?
3.  I would have an additional "card" entitled "WGBH series" (which can cover a multitude of sins...)
4.  Text:  "This program is not yet clipped and may contain third party material.  Please
contact us to license a clip from the program and reference title and series.
5.  Add contact button in the field

**Comment by mccalluc** [comment]
- DB combining is cool.
- just a wgbh logo for shows outside the big 3 (the "card" above)
- try cropping the left and right of the big three logos? failing that, letter box.
- on all records, have a "License Clip" button that goes to the form.
- sort programs to top.
- add program title to index page
- more fields: broadcast date / description / length / program # / program title / series title

**Comment by mccalluc** [comment]
Image manipulation remains to be done, but everything else is covered.

**Comment by mccalluc** [comment]
@AlisonCSmith : What are the values for Series names that will be coming in from the rights DB? For a given series, will the name always be the same, or are there any sub-series?

**Comment by mccalluc** [comment]
Added a placeholder if the series is not recognized:
screen shot 2016-07-01 at 2 56 36 pm

I think this is all the code work required. I believe this could be safely deployed, and reindexed with the new data, at any point.

**Comment by mccalluc** [comment]
@foo4thought : This PR has a solr schema change that the ruby code relies on. I think the safest thing would be to spin up a new server, but it could also probably be done on the current server, if we can tolerate a little downtime. Do you want to choose a course forward, and then I'll help you go through it?

(Stock sales does not use the server swapping strategy that we have in place for the other sites; perhaps it should.)

**Comment by foo4thought** [comment]
changing the solr schema seems like a big deal with lots of potentially hard-to-foresee consequences; I like the notion of testing such change on an "offline" instance of the app

**Comment by mccalluc** [comment]
@foo4thought : do you want to set up a new server so we can see what this looks like? How should we move this forward?

**Comment by afred** [comment]
@foo4thought @Muraszko @AlisonCSmith  ... picking up the conversation where @mccalluc left off...

I'm in favor of setting up a workflow for Stock Sales similar to that of other sites, where we deploy first to a "demo" server for QA and then make it "go live".

This will take some time to set up, whether we implement the same infrastructure machinery as our other sites, or whether we do something simpler.

If we need the PR to be live before taking the time to set this up, then we'd be looking at just running the deployment script as it's currently set up, followed by an ad-hoc QA session. If we discover any bugs, we could try to "fall forward" and fix them quickly, or try to rollback. In either case, the site would be down during any repairs.

**Comment by AlisonCSmith** [comment]
Hello all,
I know that Chuck is very busy finishing up his last hours of work here.   A couple of points and questions:
1. We are not in a great rush;  we can take the time required to set up the demo server
2.  How long would it take to set up the demo server and what kind of cost would be involved?
3.  Should we decide to go forward without the demo server, do you have any idea how
much time potentially the site could be down?

Thank you!
Alison


Be sure to visit our website: www.wgbhstocksales.org
WGBH: The Power of Public Media

**Comment by afred** [comment]
**_Conversation moved to email_**

**Comment by mccalluc** [comment]
Closing old stale PRs. I won't touch the branch, so if you want to open a new one, feel free. I probably do not need to belong to the WGBH org.

**Comment by afred** [comment]
thanks @mccalluc. Yes, we'll get you out of the Github org soon. But if you can close tix you know are stale, and save us a few cycles for trying to ascertain that for ourselves, then much obliged!

**Pull request closed without merging**
