### PR TITLE
Thumbs conform to spec?

### PR DESCRIPTION
**Pull request by mccalluc**
@afred: please review.

- We don't actually have semibold Witney: It comes out thin if I set that in the CSS.
- The color is the correct dark-blue, as far as I know.

screen shot 2015-09-28 at 12 38 00 pm

### CODE REVIEW

**Comment by lisarosenthal** [comment]
Do you know what weights are available? It looks bolder than the body copy, so might be ok.

**Comment by lisarosenthal** [comment]
Do you know what weights are available? It looks bolder than the body copy, so might be ok.

**Comment by mccalluc** [comment]
@lisarosenthal : I don't think you intended to close this. Please be careful: if I hadn't noticed this the changes would not be integrated. About fonts: I've tried various values for font-weight, but I only get normal and a heavy bold. Please file a new ticket if you think is worth worrying about. The medium-bold might be available, but may not be being delivered right now.

@afred: still needs review. Fix #51.

**Comment by lisarosenthal** [comment]
Whoops sorry about that, still getting used to using GitHub.

**Comment by lisarosenthal** [comment]
@mccalluc  Sorry about that, still getting used to using GitHub. I'm not really familiar with how the fonts are delivered so  med-bold might be available at another/later time?

**Pull request merged**
